version: '3.3'

#env_file: ../secret/prod.env

services:
  fuseki:
    image: fcore/jena:0.1.4
    #   labels:
    #  - "traefik.backend=fuseki"
    #  - "traefik.port=3030"
    #  - "traefik.frontend.rule=Host:${HOST_NAME};PathPrefix:/blazegraph"
    restart: on-failure
    ports:
       - "3030:3030"
    volumes:
       - /home/fils/Data/OCDDataVolumes/jena/data:/data
    networks:
       - web
    command: ["./fuseki-server", "--config=settings.ttl"]

  golden:
      image: fcore/golden:0.0.1
    ports:
     - 6789:6789
    networks:
     - web

networks:
  web:
    driver: overlay

